import React, { useState, useEffect } from 'react';
import { PDFDocument } from 'pdf-lib';
import { textToPDF } from '../../services/pdfEngine';
import { formatFileSize, downloadBlob } from '../shared/ToolWorkspaceHelper';
import {
  UploadCloud,
  FileText,
  Trash2,
  Sparkles,
  Maximize2,
  Ruler,
  Download,
  Copy,
  Check,
  RefreshCw,
} from 'lucide-react';

interface PdfPageDimensionViewProps {
  initialFile?: File | null;
}

interface PageDimensionInfo {
  page: number;
  widthPt: number;
  heightPt: number;
  widthMm: number;
  heightMm: number;
  widthIn: number;
  heightIn: number;
  standardName: string;
  orientation: 'Portrait' | 'Landscape' | 'Square';
  aspectRatio: string;
  pixels300Dpi: string;
}

export const PdfPageDimensionView: React.FC<PdfPageDimensionViewProps> = ({ initialFile }) => {
  const [file, setFile] = useState<File | null>(initialFile || null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [dimensions, setDimensions] = useState<PageDimensionInfo[]>([]);
  const [copied, setCopied] = useState(false);

  // Load sample document
  const handleLoadDemo = async () => {
    try {
      setIsProcessing(true);
      const sampleText = `DIMENSIONAL GEOMETRY SPECIFICATION SHEET
Standard ISO 216 & ANSI Page Measurement Specimen
Generated by Hello PDF Geometric Engine

Section 1: Standard Metric & Imperial Conversions
- 1 typographic point (pt) = 1/72 inch = 0.352778 millimeters
- Standard A4 Dimensions: 595.28 pt x 841.89 pt (210 x 297 mm)
- Standard US Letter: 612.00 pt x 792.00 pt (8.5 x 11 inches)

Section 2: High Resolution Prepress Guidelines
For 300 DPI high-definition offset printing:
- A4 target raster resolution: 2480 x 3508 pixels
- US Letter target raster resolution: 2550 x 3300 pixels
Verify physical crop marks and bleed margins before digital plate exposure.`;

      const bytes = await textToPDF(sampleText, 'Dimensional_Geometry_Specimen');
      const demoFile = new File([bytes as any], 'Dimensional_Geometry_Specimen.pdf', { type: 'application/pdf' });
      setFile(demoFile);
    } catch (err) {
      console.error('Failed to create sample', err);
    } finally {
      setIsProcessing(false);
    }
  };

  // Inspect dimensions of actual PDF pages
  useEffect(() => {
    if (!file) {
      setDimensions([]);
      return;
    }

    let isCancelled = false;

    const inspectDimensions = async () => {
      try {
        setIsProcessing(true);
        const arrayBuffer = await file.arrayBuffer();
        const pdfDoc = await PDFDocument.load(arrayBuffer, { ignoreEncryption: true });
        if (isCancelled) return;

        const pages = pdfDoc.getPages();
        const list: PageDimensionInfo[] = pages.map((page, index) => {
          const { width, height } = page.getSize();
          const wPt = Math.round(width * 100) / 100;
          const hPt = Math.round(height * 100) / 100;

          const wMm = Math.round(wPt * 0.352778 * 10) / 10;
          const hMm = Math.round(hPt * 0.352778 * 10) / 10;

          const wIn = Math.round((wPt / 72) * 100) / 100;
          const hIn = Math.round((hPt / 72) * 100) / 100;

          // Orientation
          const orientation: 'Portrait' | 'Landscape' | 'Square' =
            wPt > hPt ? 'Landscape' : hPt > wPt ? 'Portrait' : 'Square';

          // Detect standard paper
          const minD = Math.min(wPt, hPt);
          const maxD = Math.max(wPt, hPt);

          let standardName = 'Custom';
          if (Math.abs(minD - 595.28) < 5 && Math.abs(maxD - 841.89) < 5) {
            standardName = 'A4 (ISO 216)';
          } else if (Math.abs(minD - 612) < 5 && Math.abs(maxD - 792) < 5) {
            standardName = 'US Letter (ANSI A)';
          } else if (Math.abs(minD - 612) < 5 && Math.abs(maxD - 1008) < 5) {
            standardName = 'US Legal';
          } else if (Math.abs(minD - 792) < 5 && Math.abs(maxD - 1224) < 5) {
            standardName = 'Tabloid / Ledger';
          } else if (Math.abs(minD - 841.89) < 5 && Math.abs(maxD - 1190.55) < 5) {
            standardName = 'A3 (ISO 216)';
          } else if (Math.abs(minD - 419.53) < 5 && Math.abs(maxD - 595.28) < 5) {
            standardName = 'A5 (ISO 216)';
          }

          // Aspect ratio
          const ratioVal = (maxD / minD).toFixed(3);
          const aspectRatio = `1 : ${ratioVal}`;

          // 300 DPI pixel size
          const pxW = Math.round((wPt / 72) * 300);
          const pxH = Math.round((hPt / 72) * 300);
          const pixels300Dpi = `${pxW} × ${pxH} px`;

          return {
            page: index + 1,
            widthPt: wPt,
            heightPt: hPt,
            widthMm: wMm,
            heightMm: hMm,
            widthIn: wIn,
            heightIn: hIn,
            standardName,
            orientation,
            aspectRatio,
            pixels300Dpi,
          };
        });

        setDimensions(list);
      } catch (err) {
        console.warn('Page dimensions inspection error:', err);
      } finally {
        if (!isCancelled) {
          setIsProcessing(false);
        }
      }
    };

    inspectDimensions();

    return () => {
      isCancelled = true;
    };
  }, [file]);

  const primary = dimensions[0] || null;

  const handleCopyReport = () => {
    if (!primary) return;
    const report = `HELLO PDF - PAGE DIMENSIONS & RESOLUTION REPORT
Document: ${file?.name || 'document.pdf'}
Generated: ${new Date().toLocaleString()}

PRIMARY PAGE 1 GEOMETRY:
- Standard Classification: ${primary.standardName}
- Orientation: ${primary.orientation}
- Points (pt): ${primary.widthPt} × ${primary.heightPt} pt
- Millimeters (mm): ${primary.widthMm} × ${primary.heightMm} mm
- Inches (in): ${primary.widthIn} × ${primary.heightIn} inches
- Aspect Ratio: ${primary.aspectRatio}
- Target 300 DPI Prepress Resolution: ${primary.pixels300Dpi}

ALL PAGES BREAKDOWN:
${dimensions
  .map(
    (d) =>
      `Page ${d.page}: ${d.standardName} (${d.orientation}) | ${d.widthPt}×${d.heightPt} pt | ${d.widthMm}×${d.heightMm} mm | ${d.widthIn}×${d.heightIn} in`
  )
  .join('\n')}`;

    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownloadReport = () => {
    if (!primary) return;
    const report = `HELLO PDF - PAGE DIMENSIONS & RESOLUTION REPORT
Document: ${file?.name || 'document.pdf'}
Generated: ${new Date().toLocaleString()}

PRIMARY PAGE 1 GEOMETRY:
- Standard Classification: ${primary.standardName}
- Orientation: ${primary.orientation}
- Points (pt): ${primary.widthPt} × ${primary.heightPt} pt
- Millimeters (mm): ${primary.widthMm} × ${primary.heightMm} mm
- Inches (in): ${primary.widthIn} × ${primary.heightIn} inches
- Aspect Ratio: ${primary.aspectRatio}
- Target 300 DPI Prepress Resolution: ${primary.pixels300Dpi}

ALL PAGES BREAKDOWN:
${dimensions
  .map(
    (d) =>
      `Page ${d.page}: ${d.standardName} (${d.orientation}) | ${d.widthPt}×${d.heightPt} pt | ${d.widthMm}×${d.heightMm} mm | ${d.widthIn}×${d.heightIn} in`
  )
  .join('\n')}`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    downloadBlob(blob, `${file?.name || 'document'}_dimensions_spec.txt`);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 p-4 rounded-2xl bg-sky-50/70 dark:bg-sky-950/30 border border-sky-200 dark:border-sky-900/50">
        <div className="flex items-center gap-2.5">
          <Ruler className="w-5 h-5 text-sky-600 dark:text-sky-400 shrink-0" />
          <div>
            <h4 className="text-xs font-bold text-neutral-900 dark:text-neutral-100">
              PDF Page Dimensions, DPI & Geometry Inspector
            </h4>
            <p className="text-[11px] text-neutral-600 dark:text-neutral-400">
              Inspect exact page geometry in typographic points, millimeters, inches, standard paper sizes, and 300 DPI print resolutions.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={handleLoadDemo}
          disabled={isProcessing}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-sky-600 hover:bg-sky-700 text-white text-xs font-bold transition-all shadow-xs cursor-pointer shrink-0 disabled:opacity-50"
        >
          <Sparkles className="w-3.5 h-3.5" />
          <span>Try with Sample PDF</span>
        </button>
      </div>

      {/* Upload zone */}
      {!file ? (
        <div className="relative border-2 border-dashed rounded-3xl p-10 text-center border-neutral-300 dark:border-neutral-700 hover:border-sky-500 dark:hover:border-sky-500 bg-neutral-50/40 dark:bg-neutral-900/40 cursor-pointer transition-colors">
          <input
            type="file"
            accept=".pdf"
            onChange={(e) => {
              if (e.target.files && e.target.files[0]) {
                setFile(e.target.files[0]);
              }
            }}
            className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
          />
          <div className="flex flex-col items-center justify-center pointer-events-none">
            <div className="w-12 h-12 rounded-2xl bg-sky-100 dark:bg-sky-950/60 text-sky-600 dark:text-sky-400 flex items-center justify-center mb-3">
              <UploadCloud className="w-6 h-6" />
            </div>
            <p className="text-sm font-bold text-neutral-800 dark:text-neutral-200">
              Upload PDF to Inspect Dimensions
            </p>
            <p className="text-xs text-neutral-500 mt-1">
              Select any PDF to detect paper format (A4, Letter), points, mm, and inches
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-5">
          {/* File bar */}
          <div className="flex items-center justify-between p-3.5 rounded-2xl bg-white dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-800">
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-sky-600 shrink-0" />
              <div>
                <p className="text-xs font-bold text-neutral-900 dark:text-neutral-100">{file.name}</p>
                <p className="text-[11px] text-neutral-500">
                  {formatFileSize(file.size)} • {dimensions.length} Pages Analyzed
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={() => {
                setFile(null);
                setDimensions([]);
              }}
              className="p-2 text-neutral-400 hover:text-red-500 cursor-pointer"
              title="Remove File"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>

          {/* Primary Page 1 Metrics Cards */}
          {primary && (
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="p-4 rounded-2xl bg-white dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-800 text-center shadow-2xs">
                <span className="text-[10px] font-bold text-neutral-500 uppercase block mb-1">Standard Format</span>
                <p className="text-lg font-black text-sky-600 dark:text-sky-400">{primary.standardName}</p>
                <span className="text-[10px] text-neutral-500 font-semibold">{primary.orientation}</span>
              </div>

              <div className="p-4 rounded-2xl bg-white dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-800 text-center shadow-2xs">
                <span className="text-[10px] font-bold text-neutral-500 uppercase block mb-1">Typographic Points</span>
                <p className="text-lg font-black text-neutral-900 dark:text-white font-mono">
                  {primary.widthPt} × {primary.heightPt}
                </p>
                <span className="text-[10px] text-neutral-500">pt (72 pt / inch)</span>
              </div>

              <div className="p-4 rounded-2xl bg-white dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-800 text-center shadow-2xs">
                <span className="text-[10px] font-bold text-neutral-500 uppercase block mb-1">Millimeters</span>
                <p className="text-lg font-black text-neutral-900 dark:text-white font-mono">
                  {primary.widthMm} × {primary.heightMm}
                </p>
                <span className="text-[10px] text-neutral-500">
                  {primary.widthIn} × {primary.heightIn} inches
                </span>
              </div>

              <div className="p-4 rounded-2xl bg-white dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-800 text-center shadow-2xs">
                <span className="text-[10px] font-bold text-neutral-500 uppercase block mb-1">300 DPI Prepress</span>
                <p className="text-sm font-black text-neutral-900 dark:text-white font-mono mt-1">
                  {primary.pixels300Dpi}
                </p>
                <span className="text-[10px] text-neutral-500">Print raster target</span>
              </div>
            </div>
          )}

          {/* Detailed Per-Page Geometry Table */}
          <div className="p-5 rounded-2xl bg-white dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-800 shadow-2xs space-y-4">
            <div className="flex items-center justify-between border-b border-neutral-200 dark:border-neutral-800 pb-3">
              <span className="text-xs font-bold text-neutral-700 dark:text-neutral-300 uppercase tracking-wider">
                Full Document Page Geometry Breakdown
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopyReport}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-neutral-100 dark:bg-neutral-800 hover:bg-neutral-200 dark:hover:bg-neutral-700 text-xs font-bold transition-colors cursor-pointer"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied!' : 'Copy Spec'}</span>
                </button>
                <button
                  type="button"
                  onClick={handleDownloadReport}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-neutral-900 dark:bg-white text-white dark:text-neutral-900 text-xs font-bold hover:bg-neutral-800 transition-colors cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download Spec (.txt)</span>
                </button>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-neutral-200 dark:border-neutral-800 text-[10px] font-bold text-neutral-500 uppercase">
                    <th className="pb-2">Page</th>
                    <th className="pb-2">Standard</th>
                    <th className="pb-2">Orientation</th>
                    <th className="pb-2 font-mono">Points (pt)</th>
                    <th className="pb-2 font-mono">Metric (mm)</th>
                    <th className="pb-2 font-mono">Imperial (in)</th>
                    <th className="pb-2 font-mono text-right">300 DPI Prepress</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-100 dark:divide-neutral-800">
                  {dimensions.map((d) => (
                    <tr key={d.page} className="hover:bg-neutral-50/50 dark:hover:bg-neutral-900/50">
                      <td className="py-2.5 font-bold text-neutral-900 dark:text-neutral-100">
                        Page {d.page}
                      </td>
                      <td className="py-2.5 text-sky-600 dark:text-sky-400 font-medium">
                        {d.standardName}
                      </td>
                      <td className="py-2.5 text-neutral-600 dark:text-neutral-400">
                        {d.orientation}
                      </td>
                      <td className="py-2.5 font-mono text-neutral-700 dark:text-neutral-300">
                        {d.widthPt} × {d.heightPt}
                      </td>
                      <td className="py-2.5 font-mono text-neutral-700 dark:text-neutral-300">
                        {d.widthMm} × {d.heightMm}
                      </td>
                      <td className="py-2.5 font-mono text-neutral-700 dark:text-neutral-300">
                        {d.widthIn} × {d.heightIn}
                      </td>
                      <td className="py-2.5 font-mono text-neutral-500 text-right">
                        {d.pixels300Dpi}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
